version: '3'
services:
  pgadmin4:
    image: dpage/pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - $PORT:80
