version: '3'
services:
  pgadmin4:
    image: dpage/pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
